version: '3.8'
services:
  statistics:
    build: ./statistics/service
    image: statistics
    container_name: service
    ports:
      - "9090:9090"
      - "9091:9091"
    depends_on:
      - statdb
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://statdb:5432/statdb
      - SPRING_DATASOURCE_USERNAME=name
      - SPRING_DATASOURCE_PASSWORD=password

  statdb:
    image: postgres:14-alpine
    container_name: statdb
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=name
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=statdb

  #server:
  #  build: ./server
  #  image: server
  #  container_name: server
  #  ports:
  #    - "8080:8080"
  #  depends_on:
  #    - maindb
  #    - statistics
  #  environment:
  #    - SPRING_DATASOURCE_URL=jdbc:postgresql://maindb:5432/maindb
  #    - SPRING_DATASOURCE_USERNAME=name
  #    - SPRING_DATASOURCE_PASSWORD=password
  #    - STATS_SERVER_URL=http://server:9090
#
  #maindb:
  #  image: postgres:14-alpine
  #  container_name: maindb
  #  ports:
  #    - "6542:5432"
  #  environment:
  #    - POSTGRES_USER=name
  #    - POSTGRES_PASSWORD=password
  #    - POSTGRES_DB=main-service